import os
import logging
import subprocess
from datetime import datetime
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

def generate_report_data(task_id: str, task_status_info: Dict[str, Any], history_entry: Optional[Any]) -> Dict[str, Any]:
    """
    整合任務資訊生成報告數據
    """
    from .. import settings
    
    # 基礎資訊
    filename = history_entry.filename if history_entry else "Unknown"
    status = task_status_info.get("status", "UNKNOWN")
    
    # 處理時間
    elapsed = history_entry.duration_seconds if history_entry else None
    
    # 語言與格式 (從 options 中獲取，如果有的話)
    # 注意：task_status_info 可能不包含原始 options，這裡嘗試從 result 中推斷
    source_lang = "Auto"
    target_langs = "Unknown"
    subtitle_format = "ass/srt"
    
    # 嘗試從 task_result 獲取更多資訊
    warnings = task_status_info.get("warnings", [])
    error_message = task_status_info.get("message") if status == "FAILURE" else None
    
    # 模型與 Provider
    # 這裡使用當前設定，因為任務執行時通常使用這些設定
    whisper_model = os.getenv("WHISPER_MODEL", settings.WHISPER_MODEL)
    translate_provider = settings.TRANSLATE_PROVIDER
    
    return {
        "task_id": task_id,
        "filename": filename,
        "status": status,
        "source_lang": source_lang,
        "target_langs": target_langs,
        "subtitle_format": subtitle_format,
        "elapsed_seconds": elapsed,
        "whisper_model": whisper_model,
        "translate_provider": translate_provider,
        "warnings": warnings,
        "error_message": error_message,
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    }

def render_markdown(data: Dict[str, Any]) -> str:
    """
    將數據渲染為 Markdown 格式
    """
    elapsed_str = f"{data['elapsed_seconds']:.2f}s" if data['elapsed_seconds'] is not None else "N/A"
    
    md = f"""# Subtitle Processing Report

## Basic Info
- **Task ID**: {data['task_id']}
- **Filename**: {data['filename']}
- **Generated At**: {data['generated_at']}

## Processing Details
- **Status**: {data['status']}
- **Duration**: {elapsed_str}
- **Whisper Model**: {data['whisper_model']}
- **Translate Provider**: {data['translate_provider']}

## Language & Format
- **Source Language**: {data['source_lang']}
- **Target Languages**: {data['target_langs']}
- **Output Format**: {data['subtitle_format']}
"""

    if data['warnings']:
        md += "\n## Warnings\n"
        for warning in data['warnings']:
            md += f"- {warning}\n"

    if data['error_message']:
        md += f"\n## Error Details\n- **Message**: {data['error_message']}\n"

    md += "\n---\n*Generated by AI Subtitle Tool*"
    return md

def render_pdf(markdown_content: str) -> bytes:
    """
    將 Markdown 轉換為 PDF
    使用 manus-md-to-pdf 工具
    """
    import uuid
    tmp_md = f"/tmp/{uuid.uuid4()}.md"
    tmp_pdf = f"/tmp/{uuid.uuid4()}.pdf"
    
    try:
        with open(tmp_md, "w", encoding="utf-8") as f:
            f.write(markdown_content)
        
        # 使用系統預裝的 manus-md-to-pdf 工具
        result = subprocess.run(["manus-md-to-pdf", tmp_md, tmp_pdf], capture_output=True, text=True)
        
        if result.returncode == 0 and os.path.exists(tmp_pdf):
            with open(tmp_pdf, "rb") as f:
                return f.read()
        else:
            logger.error(f"PDF conversion failed: {result.stderr}")
            raise RuntimeError(f"PDF conversion failed: {result.stderr}")
    except Exception as e:
        logger.error(f"Error rendering PDF: {e}")
        raise
    finally:
        if os.path.exists(tmp_md):
            os.remove(tmp_md)
        if os.path.exists(tmp_pdf):
            os.remove(tmp_pdf)
